/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/inventory/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List inventory alerts
         * @description Return current expiry, below-reorder, and overstock alerts.
         */
        get: operations["get_inventory_alerts_inventory_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List inventory items
         * @description List inventory with optional exact-category and reorder filters.
         */
        get: operations["get_inventory_inventory_get"];
        put?: never;
        /**
         * Create an inventory item
         * @description Create a unique SKU.
         */
        post: operations["post_inventory_inventory_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/{sku}/allocate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Allocate from an inventory lot
         * @description Allocate a positive quantity from one selected lot.
         */
        post: operations["post_allocation_inventory__sku__allocate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/{sku}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get inventory item details
         * @description Return an item with lots and calculated days of cover.
         */
        get: operations["get_inventory_item_inventory__sku__get"];
        put?: never;
        post?: never;
        /**
         * Delete an inventory item
         * @description Delete only an item without dependent lots or orders.
         */
        delete: operations["remove_inventory_item_inventory__sku__delete"];
        options?: never;
        head?: never;
        /**
         * Update an inventory item
         * @description Patch supplied mutable fields on an existing item.
         */
        patch: operations["patch_inventory_item_inventory__sku__patch"];
        trace?: never;
    };
    "/vendor/{id}/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate and price a non-committing vendor quote
         * @description Quote current local vendor availability without changing it.
         */
        post: operations["quote_vendor_vendor__id__quote_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vendor/{id}/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate and commit a vendor purchase order
         * @description Revalidate the request and reserve vendor stock in one transaction.
         */
        post: operations["order_from_vendor_vendor__id__order_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check API and database health
         * @description Report healthy only when the API can reach Postgres.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AlertType
         * @description The three alert classifications frozen for Workstream 1.
         * @enum {string}
         */
        AlertType: "EXPIRING_SOON" | "BELOW_REORDER" | "OVERSTOCKED";
        /**
         * AllocationRequest
         * @description Allocate a positive quantity from one explicitly selected lot.
         */
        AllocationRequest: {
            /** Lot Id */
            lot_id: string;
            /** Qty */
            qty: number;
        };
        /**
         * AllocationResponse
         * @description Minimal acknowledgement of a successful lot allocation.
         */
        AllocationResponse: {
            /** Sku */
            sku: string;
            /** Lot Id */
            lot_id: string;
            /** Qty */
            qty: number;
        };
        /**
         * DomainErrorResponse
         * @description Exact response envelope returned for every domain error.
         */
        DomainErrorResponse: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Remedy Hint */
            remedy_hint: string;
            /** Alternatives */
            alternatives?: {
                [key: string]: unknown;
            }[];
        };
        /**
         * InventoryAlertResponse
         * @description A typed inventory alert.
         *
         *     Lot fields are present only for expiry alerts; ``days_cover`` is present
         *     only where the classification depends on cover. A zero daily draw produces
         *     ``days_cover=null`` and does not by itself create an overstock alert.
         */
        InventoryAlertResponse: {
            type: components["schemas"]["AlertType"];
            /** Sku */
            sku: string;
            /** Message */
            message: string;
            /** Lot Id */
            lot_id?: string | null;
            /** Expiry Date */
            expiry_date?: string | null;
            /** Days Cover */
            days_cover?: number | null;
        };
        /**
         * ItemCreate
         * @description Create one inventory item.
         */
        ItemCreate: {
            /** Sku */
            sku: string;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** Unit */
            unit: string;
            /**
             * On Hand
             * @default 0
             */
            on_hand: number;
            /** Reorder Point */
            reorder_point: number;
            /** Avg Daily Draw */
            avg_daily_draw: number;
            /** Unit Cost Sgd */
            unit_cost_sgd: number | string;
            /** Preferred Vendor Id */
            preferred_vendor_id?: string | null;
            /** Dspi Series */
            dspi_series?: string | null;
        };
        /**
         * ItemDetailResponse
         * @description Item representation enriched only with lots and calculated cover.
         */
        ItemDetailResponse: {
            /** Sku */
            sku: string;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** Unit */
            unit: string;
            /** On Hand */
            on_hand: number;
            /** Reorder Point */
            reorder_point: number;
            /** Avg Daily Draw */
            avg_daily_draw: number;
            /** Unit Cost Sgd */
            unit_cost_sgd: number;
            /** Preferred Vendor Id */
            preferred_vendor_id: string | null;
            /** Dspi Series */
            dspi_series: string | null;
            /** Lots */
            lots?: components["schemas"]["LotResponse"][];
            /** Days Cover */
            days_cover: number | null;
        };
        /**
         * ItemResponse
         * @description Inventory item representation used by create, list, and update.
         */
        ItemResponse: {
            /** Sku */
            sku: string;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** Unit */
            unit: string;
            /** On Hand */
            on_hand: number;
            /** Reorder Point */
            reorder_point: number;
            /** Avg Daily Draw */
            avg_daily_draw: number;
            /** Unit Cost Sgd */
            unit_cost_sgd: number;
            /** Preferred Vendor Id */
            preferred_vendor_id: string | null;
            /** Dspi Series */
            dspi_series: string | null;
        };
        /**
         * ItemUpdate
         * @description Patch mutable item fields.
         *
         *     Callers should persist ``model_dump(exclude_unset=True)``. Explicit null is
         *     accepted only for the two nullable database columns.
         */
        ItemUpdate: {
            /** Name */
            name?: string | null;
            /** Category */
            category?: string | null;
            /** Unit */
            unit?: string | null;
            /** On Hand */
            on_hand?: number | null;
            /** Reorder Point */
            reorder_point?: number | null;
            /** Avg Daily Draw */
            avg_daily_draw?: number | null;
            /** Unit Cost Sgd */
            unit_cost_sgd?: number | string | null;
            /** Preferred Vendor Id */
            preferred_vendor_id?: string | null;
            /** Dspi Series */
            dspi_series?: string | null;
        };
        /**
         * LotResponse
         * @description One received inventory lot.
         */
        LotResponse: {
            /** Lot Id */
            lot_id: string;
            /** Sku */
            sku: string;
            /** Qty */
            qty: number;
            /**
             * Expiry Date
             * Format: date
             */
            expiry_date: string;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            source: components["schemas"]["LotSource"];
        };
        /**
         * LotSource
         * @description How an inventory lot entered the charity's stock.
         * @enum {string}
         */
        LotSource: "PURCHASED" | "DONATED";
        /**
         * OrderStatus
         * @description States persisted for committed purchase orders.
         * @enum {string}
         */
        OrderStatus: "PLACED" | "FULFILLED" | "CANCELLED";
        /**
         * VendorOrderRequest
         * @description Request a committing purchase order.
         */
        VendorOrderRequest: {
            /** Sku */
            sku: string;
            /** Qty */
            qty: number;
        };
        /**
         * VendorOrderResponse
         * @description Committed purchase order representation.
         */
        VendorOrderResponse: {
            /** Order Id */
            order_id: string;
            /** Vendor Id */
            vendor_id: string;
            /** Sku */
            sku: string;
            /** Qty */
            qty: number;
            status: components["schemas"]["OrderStatus"];
            /** Unit Price Sgd */
            unit_price_sgd: number;
            /**
             * Placed At
             * Format: date-time
             */
            placed_at: string;
            /**
             * Expected At
             * Format: date-time
             */
            expected_at: string;
        };
        /**
         * VendorQuoteRequest
         * @description Request a non-committing vendor quote.
         */
        VendorQuoteRequest: {
            /** Sku */
            sku: string;
            /** Qty */
            qty: number;
        };
        /**
         * VendorQuoteResponse
         * @description Deterministic local quote, without DSPI implementation details.
         */
        VendorQuoteResponse: {
            /** Vendor Id */
            vendor_id: string;
            /** Sku */
            sku: string;
            /** Qty */
            qty: number;
            /** Available */
            available: boolean;
            /** Unit Price Sgd */
            unit_price_sgd: number;
            /** Total Price Sgd */
            total_price_sgd: number;
            /**
             * Expected At
             * Format: date-time
             */
            expected_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_inventory_alerts_inventory_alerts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryAlertResponse"][];
                };
            };
            /** @description Standardized domain error response. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
        };
    };
    get_inventory_inventory_get: {
        parameters: {
            query?: {
                category?: string | null;
                below_reorder?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemResponse"][];
                };
            };
            /** @description Standardized domain error response. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
        };
    };
    post_inventory_inventory_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemResponse"];
                };
            };
            /** @description Standardized domain error response. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description Standardized domain error response. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description Standardized domain error response. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
        };
    };
    post_allocation_inventory__sku__allocate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sku: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AllocationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllocationResponse"];
                };
            };
            /** @description Standardized domain error response. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description Standardized domain error response. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description Standardized domain error response. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description Standardized domain error response. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
        };
    };
    get_inventory_item_inventory__sku__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sku: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemDetailResponse"];
                };
            };
            /** @description Standardized domain error response. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description Standardized domain error response. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
        };
    };
    remove_inventory_item_inventory__sku__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sku: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Standardized domain error response. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description Standardized domain error response. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description Standardized domain error response. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
        };
    };
    patch_inventory_item_inventory__sku__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sku: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemResponse"];
                };
            };
            /** @description Standardized domain error response. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description Standardized domain error response. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description Standardized domain error response. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
        };
    };
    quote_vendor_vendor__id__quote_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Demo-Rate-Limit"?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VendorQuoteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VendorQuoteResponse"];
                };
            };
            /** @description Vendor minimum order was not met. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description Vendor or SKU was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description Vendor stock cannot fulfil the request. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description Lead time or request validation failed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description Demo rate limit; retry using the Retry-After header. */
            429: {
                headers: {
                    /** @description Seconds until the demo request can be retried. */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
        };
    };
    order_from_vendor_vendor__id__order_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Demo-Rate-Limit"?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VendorOrderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VendorOrderResponse"];
                };
            };
            /** @description Vendor minimum order was not met. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description Vendor or SKU was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description Vendor stock cannot fulfil the request. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description Lead time or request validation failed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description Demo rate limit; retry using the Retry-After header. */
            429: {
                headers: {
                    /** @description Seconds until the demo request can be retried. */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
