/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as RequestRouteRouteImport } from './routes/request/route'
import { Route as authAgentRouteImport } from './routes/(auth)/agent'
import { Route as authDashboardRouteImport } from './routes/(auth)/dashboard'
import { Route as authFeedbackRouteImport } from './routes/(auth)/feedback'
import { Route as authOrdersRouteImport } from './routes/(auth)/orders'
import { Route as authPeopleRouteImport } from './routes/(auth)/people'
import { Route as authSettingsRouteImport } from './routes/(auth)/settings'
import { Route as authStockRouteImport } from './routes/(auth)/stock'
import { Route as publicLoginRouteImport } from './routes/(public)/login'
import { Route as publicSignupRouteImport } from './routes/(public)/signup'
import { Route as publicRequestTokenRouteImport } from './routes/(public)/request_/$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRouteRoute = RequestRouteRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const authAgentRoute = authAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => authRouteRoute,
} as any)
const authDashboardRoute = authDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => authRouteRoute,
} as any)
const authFeedbackRoute = authFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => authRouteRoute,
} as any)
const authOrdersRoute = authOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => authRouteRoute,
} as any)
const authPeopleRoute = authPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => authRouteRoute,
} as any)
const authSettingsRoute = authSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => authRouteRoute,
} as any)
const authStockRoute = authStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => authRouteRoute,
} as any)
const publicLoginRoute = publicLoginRouteImport.update({
  id: '/(public)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const publicSignupRoute = publicSignupRouteImport.update({
  id: '/(public)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const publicRequestTokenRoute = publicRequestTokenRouteImport.update({
  id: '/(public)/request_/$token',
  path: '/request/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/request': typeof RequestRouteRoute
  '/agent': typeof authAgentRoute
  '/dashboard': typeof authDashboardRoute
  '/feedback': typeof authFeedbackRoute
  '/orders': typeof authOrdersRoute
  '/people': typeof authPeopleRoute
  '/settings': typeof authSettingsRoute
  '/stock': typeof authStockRoute
  '/login': typeof publicLoginRoute
  '/signup': typeof publicSignupRoute
  '/request/$token': typeof publicRequestTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/request': typeof RequestRouteRoute
  '/agent': typeof authAgentRoute
  '/dashboard': typeof authDashboardRoute
  '/feedback': typeof authFeedbackRoute
  '/orders': typeof authOrdersRoute
  '/people': typeof authPeopleRoute
  '/settings': typeof authSettingsRoute
  '/stock': typeof authStockRoute
  '/login': typeof publicLoginRoute
  '/signup': typeof publicSignupRoute
  '/request/$token': typeof publicRequestTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/request': typeof RequestRouteRoute
  '/(auth)/agent': typeof authAgentRoute
  '/(auth)/dashboard': typeof authDashboardRoute
  '/(auth)/feedback': typeof authFeedbackRoute
  '/(auth)/orders': typeof authOrdersRoute
  '/(auth)/people': typeof authPeopleRoute
  '/(auth)/settings': typeof authSettingsRoute
  '/(auth)/stock': typeof authStockRoute
  '/(public)/login': typeof publicLoginRoute
  '/(public)/signup': typeof publicSignupRoute
  '/(public)/request_/$token': typeof publicRequestTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/request'
    | '/agent'
    | '/dashboard'
    | '/feedback'
    | '/orders'
    | '/people'
    | '/settings'
    | '/stock'
    | '/login'
    | '/signup'
    | '/request/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/request'
    | '/agent'
    | '/dashboard'
    | '/feedback'
    | '/orders'
    | '/people'
    | '/settings'
    | '/stock'
    | '/login'
    | '/signup'
    | '/request/$token'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/request'
    | '/(auth)/agent'
    | '/(auth)/dashboard'
    | '/(auth)/feedback'
    | '/(auth)/orders'
    | '/(auth)/people'
    | '/(auth)/settings'
    | '/(auth)/stock'
    | '/(public)/login'
    | '/(public)/signup'
    | '/(public)/request_/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  RequestRouteRoute: typeof RequestRouteRoute
  publicLoginRoute: typeof publicLoginRoute
  publicSignupRoute: typeof publicSignupRoute
  publicRequestTokenRoute: typeof publicRequestTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/agent': {
      id: '/(auth)/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof authAgentRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/dashboard': {
      id: '/(auth)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authDashboardRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/feedback': {
      id: '/(auth)/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof authFeedbackRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/orders': {
      id: '/(auth)/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof authOrdersRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/people': {
      id: '/(auth)/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof authPeopleRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/settings': {
      id: '/(auth)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof authSettingsRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/stock': {
      id: '/(auth)/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof authStockRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/signup': {
      id: '/(public)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof publicSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/request_/$token': {
      id: '/(public)/request_/$token'
      path: '/request/$token'
      fullPath: '/request/$token'
      preLoaderRoute: typeof publicRequestTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface authRouteRouteChildren {
  authAgentRoute: typeof authAgentRoute
  authDashboardRoute: typeof authDashboardRoute
  authFeedbackRoute: typeof authFeedbackRoute
  authOrdersRoute: typeof authOrdersRoute
  authPeopleRoute: typeof authPeopleRoute
  authSettingsRoute: typeof authSettingsRoute
  authStockRoute: typeof authStockRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authAgentRoute: authAgentRoute,
  authDashboardRoute: authDashboardRoute,
  authFeedbackRoute: authFeedbackRoute,
  authOrdersRoute: authOrdersRoute,
  authPeopleRoute: authPeopleRoute,
  authSettingsRoute: authSettingsRoute,
  authStockRoute: authStockRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  RequestRouteRoute: RequestRouteRoute,
  publicLoginRoute: publicLoginRoute,
  publicSignupRoute: publicSignupRoute,
  publicRequestTokenRoute: publicRequestTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
