#!/usr/bin/env bash
# Write short-lived static keys to aws/credentials (gitignored).
#
# You almost certainly DON'T need this: the orchestrator reads the SSO profile
# directly and refreshes on its own. This exists only for tools that cannot do
# SSO — a bare Docker container, or a teammate's script that expects static keys.
#
# These keys expire in ~12h and do NOT auto-refresh. Re-run to renew.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export AWS_CONFIG_FILE="$ROOT/aws/config"
PROFILE="${AWS_PROFILE:-hackathon}"
OUT="$ROOT/aws/credentials"

aws sts get-caller-identity --profile "$PROFILE" >/dev/null 2>&1 || {
  echo "No valid session. Run: make aws-login"; exit 1; }

creds="$(aws configure export-credentials --profile "$PROFILE" --format env-no-export)"
akid=$(sed -n 's/^AWS_ACCESS_KEY_ID=//p'     <<<"$creds")
secret=$(sed -n 's/^AWS_SECRET_ACCESS_KEY=//p' <<<"$creds")
token=$(sed -n 's/^AWS_SESSION_TOKEN=//p'    <<<"$creds")

umask 077
cat > "$OUT" <<CREDS
# GENERATED by scripts/aws-export-credentials.sh — do not commit, do not edit.
# Short-lived (~12h) and does NOT auto-refresh. Re-run the script to renew.
[$PROFILE]
aws_access_key_id = $akid
aws_secret_access_key = $secret
aws_session_token = $token
CREDS
chmod 600 "$OUT"
echo "wrote $OUT (mode 600, gitignored)"
