// src/routes/approvals.tsx
import { createFileRoute } from "@tanstack/react-router";
import { useState, useEffect } from "react";
import { orchestratorClient } from "@/lib/api";
import { useAuth } from "@/lib/use-auth";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Bot, CheckCircle, XCircle, Clock, ArrowRight } from "lucide-react";
import { toast } from "sonner";

export const Route = createFileRoute("/approvals")({
  component: ApprovalsPage,
});

function ApprovalsPage() {
  const { user } = useAuth();
  const [runs, setRuns] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  const fetchRuns = async () => {
    setIsLoading(true);
    const { data, error } = await orchestratorClient.GET("/agent/runs");
    if (error) {
      toast.error("Failed to load agent runs");
    } else {
      setRuns(Array.isArray(data) ? data : []);
    }
    setIsLoading(false);
  };

  useEffect(() => {
    fetchRuns();
  }, []);

  // The Human-in-the-loop decision!
  const handleDecision = async (
    threadId: string,
    decision: "approved" | "rejected",
  ) => {
    const { error } = await orchestratorClient.POST(
      "/agent/runs/{thread_id}/decision",
      {
        params: { path: { thread_id: threadId } },
        body: {
          decision: decision,
          decided_by: user?.email || "admin@charity.org",
        },
      },
    );

    if (error) {
      toast.error(`Failed to submit decision for ${threadId}`);
    } else {
      toast.success(`Run successfully ${decision}!`);
      fetchRuns(); // Refresh the list
    }
  };

  // Trigger a new AI Run manually
  const startNewRun = async () => {
    const { error } = await orchestratorClient.POST("/agent/runs", {
      body: { charity_type: "A" },
    });

    if (error) {
      toast.error("Failed to start AI run");
    } else {
      toast.success("AI Orchestrator started planning!");
      fetchRuns();
    }
  };

  return (
    <div className="p-8 max-w-5xl mx-auto space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">
            AI Agent Approvals
          </h1>
          <p className="text-muted-foreground mt-1">
            Review and approve automated logistics plans generated by LangGraph.
          </p>
        </div>
        <Button
          onClick={startNewRun}
          className="gap-2 bg-indigo-600 hover:bg-indigo-700"
        >
          <Bot className="h-4 w-4" /> Trigger Planning Run
        </Button>
      </div>

      <div className="grid gap-6">
        {isLoading ? (
          <p className="text-stone-500 py-8 text-center animate-pulse">
            Loading AI workflows...
          </p>
        ) : runs.length === 0 ? (
          <Card className="border-stone-200 border-dashed shadow-none">
            <CardContent className="flex flex-col items-center justify-center h-48 text-stone-500">
              <Bot className="h-12 w-12 text-stone-300 mb-4" />
              <p>No active agent runs.</p>
            </CardContent>
          </Card>
        ) : (
          runs.map((run) => (
            <Card
              key={run.thread_id}
              className={`shadow-sm border-stone-200 ${run.status === "paused" ? "border-amber-300 ring-1 ring-amber-100" : ""}`}
            >
              <CardHeader className="pb-3 flex flex-row justify-between items-start">
                <div>
                  <div className="flex items-center gap-2 mb-2">
                    <CardTitle className="text-lg">Workflow Thread</CardTitle>
                    <Badge
                      variant="outline"
                      className="font-mono text-xs bg-stone-50"
                    >
                      {run.thread_id}
                    </Badge>
                  </div>
                  <CardDescription>
                    Review the AI's proposed action based on current unmet
                    needs.
                  </CardDescription>
                </div>

                {run.status === "paused" && (
                  <Badge className="bg-amber-100 text-amber-800 border-amber-200 gap-1.5 px-3 py-1 text-sm font-medium">
                    <Clock className="h-3.5 w-3.5" /> Requires Approval
                  </Badge>
                )}
                {run.status === "approved" && (
                  <Badge className="bg-emerald-100 text-emerald-800 border-emerald-200 gap-1.5 px-3 py-1">
                    <CheckCircle className="h-3.5 w-3.5" /> Approved
                  </Badge>
                )}
                {run.status === "rejected" && (
                  <Badge variant="destructive" className="gap-1.5 px-3 py-1">
                    <XCircle className="h-3.5 w-3.5" /> Rejected
                  </Badge>
                )}
              </CardHeader>

              <CardContent>
                <div className="bg-stone-50 border border-stone-100 rounded-lg p-4 text-sm font-medium text-stone-700 flex items-center justify-between">
                  {/* Depending on how your LangGraph returns state, you can render the actual AI proposal here */}
                  <div className="flex items-center gap-3">
                    <Bot className="h-5 w-5 text-indigo-500" />
                    <span>
                      The agent proposes creating a Purchase Order to resolve{" "}
                      <span className="font-bold">5 shortages</span>.
                    </span>
                  </div>
                  <Button variant="link" className="text-indigo-600 gap-1">
                    View Details <ArrowRight className="h-4 w-4" />
                  </Button>
                </div>
              </CardContent>

              {run.status === "paused" && (
                <CardFooter className="bg-stone-50/50 border-t border-stone-100 mt-2 py-4 flex justify-end gap-3 rounded-b-xl">
                  <Button
                    variant="outline"
                    className="border-destructive/50 text-destructive hover:bg-destructive hover:text-white"
                    onClick={() => handleDecision(run.thread_id, "rejected")}
                  >
                    <XCircle className="h-4 w-4 mr-2" /> Reject Plan
                  </Button>
                  <Button
                    className="bg-emerald-600 hover:bg-emerald-700 text-white"
                    onClick={() => handleDecision(run.thread_id, "approved")}
                  >
                    <CheckCircle className="h-4 w-4 mr-2" /> Approve & Execute
                  </Button>
                </CardFooter>
              )}
            </Card>
          ))
        )}
      </div>
    </div>
  );
}
